## ingame-debug.yaml
label-debug-panel-title = 치트
checkbox-debug-panel-instant-build = 즉시 건설
checkbox-debug-panel-enable-tech = 모든 항목 건설
checkbox-debug-panel-build-anywhere = 어디서나 건설
checkbox-debug-panel-unlimited-power = 무제한 전력
checkbox-debug-panel-instant-charge = 즉시 충전
checkbox-debug-panel-disable-visibility-checks = 가시성 검사 해제
button-debug-panel-give-cash = $20,000 지급
button-debug-panel-give-cash-all = 전원 자금 지급
button-debug-panel-heal-selected = 선택 유닛 회복
button-debug-panel-dispose-selected = 선택 유닛 제거
button-debug-panel-grow-resources = 자원 성장
button-debug-panel-kill-selected = 선택 유닛 파괴
button-debug-panel-clear-shroud = 미탐색 지역 제거
button-debug-panel-reset-shroud = 미탐색 지역 초기화
button-debug-panel-level-up = 레벨 업
button-debug-panel-player-experience = 플레이어 경험치
label-debug-panel-selection-title = 선택
label-debug-panel-visualizations-title = 시각화
checkbox-debug-panel-show-unit-paths = 유닛 경로 표시
checkbox-debug-panel-show-customterrain-overlay = 커스텀 지형 표시
checkbox-debug-panel-show-actor-tags = 액터 태그 표시
checkbox-debug-panel-show-combatoverlay = 전투 지오메트리 표시
checkbox-debug-panel-show-geometry = 렌더 지오메트리 표시
checkbox-debug-panel-show-terrain-overlay = 지형 지오메트리 표시
checkbox-debug-panel-show-celltrigger-overlay = 셀 트리거 표시
checkbox-debug-panel-show-actormap-overlay = 액터 맵 표시
checkbox-debug-panel-show-screenmap = 스크린 맵 표시
checkbox-debug-panel-show-hpf-overlay = HPF 오버레이 표시
