hotkey-context =
    .player = 플레이어
    .spectator = 관전자
    .chat-input = 채팅 입력
    .menu = 메뉴
    .editor = 에디터

## chat.yaml
hotkey-description-openteamchat = 팀 채팅 열기
hotkey-description-opengeneralchat = 전체 채팅 열기
hotkey-description-togglechatmode = 채팅 모드 전환
hotkey-description-autocomplete = 자동 완성

## control-groups.yaml
hotkey-description-controlgroupselect01 = 그룹 1 선택
hotkey-description-controlgroupselect02 = 그룹 2 선택
hotkey-description-controlgroupselect03 = 그룹 3 선택
hotkey-description-controlgroupselect04 = 그룹 4 선택
hotkey-description-controlgroupselect05 = 그룹 5 선택
hotkey-description-controlgroupselect06 = 그룹 6 선택
hotkey-description-controlgroupselect07 = 그룹 7 선택
hotkey-description-controlgroupselect08 = 그룹 8 선택
hotkey-description-controlgroupselect09 = 그룹 9 선택
hotkey-description-controlgroupselect10 = 그룹 0 선택
hotkey-description-controlgroupcreate01 = 그룹 1 생성
hotkey-description-controlgroupcreate02 = 그룹 2 생성
hotkey-description-controlgroupcreate03 = 그룹 3 생성
hotkey-description-controlgroupcreate04 = 그룹 4 생성
hotkey-description-controlgroupcreate05 = 그룹 5 생성
hotkey-description-controlgroupcreate06 = 그룹 6 생성
hotkey-description-controlgroupcreate07 = 그룹 7 생성
hotkey-description-controlgroupcreate08 = 그룹 8 생성
hotkey-description-controlgroupcreate09 = 그룹 9 생성
hotkey-description-controlgroupcreate10 = 그룹 0 생성
hotkey-description-controlgroupaddto01 = 그룹 1에 추가
hotkey-description-controlgroupaddto02 = 그룹 2에 추가
hotkey-description-controlgroupaddto03 = 그룹 3에 추가
hotkey-description-controlgroupaddto04 = 그룹 4에 추가
hotkey-description-controlgroupaddto05 = 그룹 5에 추가
hotkey-description-controlgroupaddto06 = 그룹 6에 추가
hotkey-description-controlgroupaddto07 = 그룹 7에 추가
hotkey-description-controlgroupaddto08 = 그룹 8에 추가
hotkey-description-controlgroupaddto09 = 그룹 9에 추가
hotkey-description-controlgroupaddto10 = 그룹 0에 추가
hotkey-description-controlgroupcombinewith01 = 그룹 1과 합치기
hotkey-description-controlgroupcombinewith02 = 그룹 2와 합치기
hotkey-description-controlgroupcombinewith03 = 그룹 3과 합치기
hotkey-description-controlgroupcombinewith04 = 그룹 4와 합치기
hotkey-description-controlgroupcombinewith05 = 그룹 5와 합치기
hotkey-description-controlgroupcombinewith06 = 그룹 6과 합치기
hotkey-description-controlgroupcombinewith07 = 그룹 7과 합치기
hotkey-description-controlgroupcombinewith08 = 그룹 8과 합치기
hotkey-description-controlgroupcombinewith09 = 그룹 9와 합치기
hotkey-description-controlgroupcombinewith10 = 그룹 0과 합치기
hotkey-description-controlgroupjumpto01 = 그룹 1로 이동
hotkey-description-controlgroupjumpto02 = 그룹 2로 이동
hotkey-description-controlgroupjumpto03 = 그룹 3으로 이동
hotkey-description-controlgroupjumpto04 = 그룹 4로 이동
hotkey-description-controlgroupjumpto05 = 그룹 5로 이동
hotkey-description-controlgroupjumpto06 = 그룹 6으로 이동
hotkey-description-controlgroupjumpto07 = 그룹 7로 이동
hotkey-description-controlgroupjumpto08 = 그룹 8로 이동
hotkey-description-controlgroupjumpto09 = 그룹 9로 이동
hotkey-description-controlgroupjumpto10 = 그룹 0으로 이동
hotkey-description-removefromcontrolgroup = 컨트롤 그룹에서 제거

## editor.yaml
hotkey-description-editorundo = 실행 취소
hotkey-description-editorredo = 다시 실행
hotkey-description-editorcopy = 복사
hotkey-description-editorquicksave = 맵 저장
hotkey-description-editorpaste = 붙여넣기
hotkey-description-editordeleteselection = 선택 영역 삭제
hotkey-description-editorselecttab = 선택 탭
hotkey-description-editortilestab = 타일 탭
hotkey-description-editoroverlaystab = 오버레이 탭
hotkey-description-editoractorstab = 액터 탭
hotkey-description-editortoolstab = 도구 탭
hotkey-description-editorhistorytab = 기록 탭
hotkey-description-editorsettingstab = 설정 탭
hotkey-description-editortogglegridoverlay = 격자 오버레이
hotkey-description-editortogglebuildableoverlay = 건설 가능 지형 오버레이
hotkey-description-editortogglemarkeroverlay = 마커 레이어 오버레이

## game.yaml
hotkey-description-cyclebase = 기지로 이동
hotkey-description-tolastevent = 마지막 레이더 이벤트로 이동
hotkey-description-toselection = 선택 유닛으로 이동
hotkey-description-selectallunits = 모든 전투 유닛 선택
hotkey-description-selectunitsbytype = 같은 종류 유닛 선택
hotkey-description-cycleharvesters = Harvester 순환 선택
hotkey-description-pause = 일시 정지 / 재개
hotkey-description-sell = 판매 모드
hotkey-description-repair = 수리 모드
hotkey-description-placebeacon = 비콘 설치
hotkey-description-cyclestatusbars = 상태 표시줄 표시 전환
hotkey-description-togglemute = 오디오 음소거 전환
hotkey-description-toggleplayerstancecolor = 관계 색상 전환
hotkey-description-takescreenshot = 스크린샷 찍기
hotkey-description-quicksave = 빠른 저장
hotkey-description-attackmove = 공격 이동
hotkey-description-stop = 정지
hotkey-description-scatter = 산개
hotkey-description-deploy = 배치
hotkey-description-guard = 경계
hotkey-description-stanceattackanything = 무조건 공격
hotkey-description-stancedefend = 방어
hotkey-description-stancereturnfire = 응사
hotkey-description-stanceholdfire = 사격 중지
hotkey-description-stopmusic = 정지
hotkey-description-pausemusic = 일시 정지 또는 재개
hotkey-description-prevmusic = 이전
hotkey-description-nextmusic = 다음

## observer.yaml
hotkey-description-observercombinedview = 모든 플레이어
hotkey-description-observerworldview = 미탐색 지역 해제
hotkey-description-replayspeedslow = 느린 속도
hotkey-description-replayspeedregular = 보통 속도
hotkey-description-replayspeedfast = 빠른 속도
hotkey-description-replayspeedmax = 최대 속도
hotkey-description-statisticsnone = 통계 끄기
hotkey-description-statisticsbasic = 기본 통계
hotkey-description-statisticseconomy = 경제 통계
hotkey-description-statisticsproduction = 생산 통계
hotkey-description-statisticssupportpowers = 지원 능력 통계
hotkey-description-statisticscombat = 전투 통계
hotkey-description-statisticsarmy = 병력 통계
hotkey-description-statisticsgraph = 통계 그래프
hotkey-description-statisticsarmygraph = 병력 가치 그래프

## production-common.yaml
hotkey-description-cycleproductionbuildings = 다음 생산 건물
hotkey-description-selectproductionbuilding = 현재 생산 건물
hotkey-description-production01 = 슬롯 01
hotkey-description-production02 = 슬롯 02
hotkey-description-production03 = 슬롯 03
hotkey-description-production04 = 슬롯 04
hotkey-description-production05 = 슬롯 05
hotkey-description-production06 = 슬롯 06
hotkey-description-production07 = 슬롯 07
hotkey-description-production08 = 슬롯 08
hotkey-description-production09 = 슬롯 09
hotkey-description-production10 = 슬롯 10
hotkey-description-production11 = 슬롯 11
hotkey-description-production12 = 슬롯 12
hotkey-description-production13 = 슬롯 13
hotkey-description-production14 = 슬롯 14
hotkey-description-production15 = 슬롯 15
hotkey-description-production16 = 슬롯 16
hotkey-description-production17 = 슬롯 17
hotkey-description-production18 = 슬롯 18
hotkey-description-production19 = 슬롯 19
hotkey-description-production20 = 슬롯 20
hotkey-description-production21 = 슬롯 21
hotkey-description-production22 = 슬롯 22
hotkey-description-production23 = 슬롯 23
hotkey-description-production24 = 슬롯 24

## supportpowers.yaml
hotkey-description-supportpower01 = 슬롯 01
hotkey-description-supportpower02 = 슬롯 02
hotkey-description-supportpower03 = 슬롯 03
hotkey-description-supportpower04 = 슬롯 04
hotkey-description-supportpower05 = 슬롯 05
hotkey-description-supportpower06 = 슬롯 06

## viewport.yaml
hotkey-description-mapscrollup = 위로 스크롤
hotkey-description-mapscrolldown = 아래로 스크롤
hotkey-description-mapscrollleft = 왼쪽으로 스크롤
hotkey-description-mapscrollright = 오른쪽으로 스크롤
hotkey-description-mapjumptotopedge = 위쪽 끝으로 이동
hotkey-description-mapjumptobottomedge = 아래쪽 끝으로 이동
hotkey-description-mapjumptoleftedge = 왼쪽 끝으로 이동
hotkey-description-mapjumptorightedge = 오른쪽 끝으로 이동
hotkey-description-mapbookmarksave01 = 북마크 1 저장
hotkey-description-mapbookmarkrestore01 = 북마크 1로 이동
hotkey-description-mapbookmarksave02 = 북마크 2 저장
hotkey-description-mapbookmarkrestore02 = 북마크 2로 이동
hotkey-description-mapbookmarksave03 = 북마크 3 저장
hotkey-description-mapbookmarkrestore03 = 북마크 3으로 이동
hotkey-description-mapbookmarksave04 = 북마크 4 저장
hotkey-description-mapbookmarkrestore04 = 북마크 4로 이동
hotkey-description-zoomin = 확대
hotkey-description-zoomout = 축소
hotkey-description-resetzoom = 확대/축소 초기화
hotkey-description-disableuserinterface = 사용자 인터페이스 숨기기
hotkey-description-disablealluserinterface = 추가 사용자 인터페이스 숨기기
